languageCode = "en"
languageName = "English"
weight = 1


title = "deyvid"
copyright = "Copy, _right?_ :thinking_face:"


[params]
  logo = "img/blogo.png"
  description = "My awesome website"
  dateFormat = "2 January 2006"
  rtl = false
  isoCode = "en"
  displayName = "EN"

[author]
  name = "deyvid m."
  image = "img/author.jpg"
  headline = "I'm only human"
  bio = "A little bit about me: "
  links = [
    { email = "mailto:deyvidmitkov@gmail.com" },
    { github = "https://github.com/deyvdim" },
    { linkedin = "https://linkedin.com/in/deyvid-mitkov" },
  ]
